#CI项目
name: MTK-ALL

#CI计划
on:
  #自动编译：每天早上4点
  #schedule:
    #- cron: 0 20 * * *
  #手动编译
  workflow_dispatch:

#CI权限
permissions: write-all

#CI任务
jobs:
  wrt_config:
    name: ${{matrix.TARGET}}_${{matrix.SOURCE}}
    strategy:
      matrix:
        TARGET: [MTK-7981, MTK-7986]
        SOURCE: [hanwckf/immortalwrt-mt798x, padavanonly/immortalwrt-mt798x]

    uses: ./.github/workflows/WRT-CORE.yml
    with:
      #编译平台
      WRT_TARGET: ${{matrix.TARGET}}
      #默认主题
      WRT_THEME: argon
      #默认主机名
      WRT_NAME: CWRT
      #默认WIFI名
      WRT_WIFI: CWRT
      #默认密码，仅作提示，修改无用
      WRT_PW: 无
      #默认地址
      WRT_IP: 192.168.10.1
      #默认源码
      WRT_URL: https://github.com/${{matrix.SOURCE}}.git
      #默认分支
      WRT_BRANCH: openwrt-21.02
